#!/bin/bash
if grep -Fq "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" /etc/apt/sources.list.d/google-chrome.list
then
    echo "Chrome PPA already exists"
else
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
fi