#!/bin/bash
if grep -Fxq "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" /etc/apt/sources.list.d/google.list
then
    echo "Chrome PPA already exists"
else
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
fi

if grep -Fxq "deb http://repository.spotify.com stable non-free" /etc/apt/sources.list.d/spotify.list
then
    echo "Spotify PPA already exists"
else
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    sudo sh -c 'echo "deb http://repository.spotify.com stable non-free" > /etc/apt/sources.list.d/spotify.list'
fi

if grep -Fxq "deb http://linux.dropbox.com/ubuntu/ xenial main" /etc/apt/sources.list.d/dropbox.list
then
    echo "Dropbox PPA already exists"
else
    sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
    sudo sh -c 'echo "deb http://linux.dropbox.com/ubuntu/ xenial main" > /etc/apt/sources.list.d/dropbox.list'
fi

if grep -Fxq "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" /etc/apt/sources.list.d/signal-xenial.list
then
    echo "Signal PPA already exists"
else
    curl -s https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add -
    echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
fi
